# -*- coding: utf-8 -*-
"""100DaysOfCode_Day73.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_lGQ6INgaDn_KioDyHET9z5qgIzQPPaD
"""

import pandas as pd

df = pd.read_csv('QueryResults.csv',names=['DATA','TAG','POSt'],header=0)

df.head()

df.tail()

df.shape

df.groupby('TAG').sum()

df.groupby('TAG').count()

df['DATA'][1]

df.DATA = pd.to_datetime(df.DATA)

df.head()

import matplotlib.pyplot as plt

print(df.columns.tolist())  # See all column names
print(df.head())

df = pd.read_csv('QueryResults.csv',names=['DATA','TAG','POSt'],header=0)

import pandas as pd

df = pd.read_csv('QueryResults.csv',names=['DATA','TAG','POSt'],header=0)

import matplotlib.pyplot as plt

df.head()

plt.figure(figsize=(16,10)) # make chart larger
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.xlabel('Date', fontsize=14)
plt.ylabel('Number of Posts', fontsize=14)
plt.ylim(0, 35000)

plt.plot(reshaped_df.index, reshaped_df.java)
plt.plot(reshaped_df.index, reshaped_df.python) # Tadah!

for column in reshaped_df.columns:
    plt.plot(reshaped_df.index, reshaped_df[column])

plt.figure(figsize=(16,10))
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.xlabel('Date', fontsize=14)
plt.ylabel('Number of Posts', fontsize=14)
plt.ylim(0, 35000)

for column in reshaped_df.columns:
    plt.plot(reshaped_df.index, reshaped_df[column],
             linewidth=3, label=reshaped_df[column].name)

plt.legend(fontsize=16)

roll_df = reshaped_df.rolling(window=6).mean()


plt.figure(figsize=(16,10))
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.xlabel('Date', fontsize=14)
plt.ylabel('Number of Posts', fontsize=14)
plt.ylim(0, 35000)

# plot the roll_df instead
for column in roll_df.columns:
    plt.plot(roll_df.index, roll_df[column],
             linewidth=3, label=roll_df[column].name)

plt.gca().xaxis.set_major_locator(mdates.AutoDateLocator())
plt.gcf().autofmt_xdate()


plt.legend(fontsize=16)

