# -*- coding: utf-8 -*-
"""100DaysOfCode_Day74.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ACK5O0vym-umSSOSVGvlKuHP8Kip2Fk
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

from IPython.display import Image, display

"""<img src="https://i.imgur.com/49FNOHj.jpg">

"""

colors = pd.read_csv('data/colors.csv')
colors.head()

colors['name'].nunique()

colors.groupby('is_trans').count()

colors.is_trans.value_counts()

sets = pd.read_csv('data/sets.csv')
sets.head()

sets.tail()

sets.sort_values('year').head()

sets[sets['year'] == 1949]

sets.sort_values('num_parts', ascending=False).head(5)

import matplotlib.pyplot as plt

sets_by_year = sets.groupby('year').count()
sets_by_year['set_num'].head()

sets_by_year['set_num'].tail()

plt.plot(sets_by_year.index, sets_by_year.set_num)

plt.plot(sets_by_year.index[:-2], sets_by_year.set_num[:-2])

themes_by_year = sets.groupby('year').agg({'theme_id':pd.Series.nunique})

themes_by_year.rename(columns = {'theme_id': 'nr themes'}, inplace = True)
themes_by_year.head()

themes_by_year.tail()

plt.plot(themes_by_year.index[:-2], themes_by_year.values[:-2])

plt.plot(themes_by_year.index[:-2], themes_by_year.values[:-2])
plt.plot(sets_by_year.index[:-2], sets_by_year.set_num[:-2])

ax1 = plt.gca() # get current axes
ax2 = ax1.twinx()

ax1 = plt.gca()
ax2 = ax1.twinx()

ax1.plot(sets_by_year.index[:-2], sets_by_year.values[:-2], color='g')
ax2.plot(themes_by_year.index[:-2], themes_by_year.values[:-2], 'b')

ax1.set_xlabel('Year')
ax1.set_ylabel('Number of Sets', color='green')
ax2.set_ylabel('Number of Themes', color='blue')

parts_per_set = sets.groupby('year').agg({'num_parts': pd.Series.mean})

parts_per_set.head()

plt.scatter(parts_per_set.index[:-2], parts_per_set.values[:-2])

set_theme_count = sets ["theme_id"].value_counts()
set_theme_count[:5]

"""<img src="https://i.imgur.com/Sg4lcjx.png">

"""

set_theme_count = pd. DataFrame({'id': set_theme_count.index,
'set_count':
set_theme_count.values})
set_theme_count.head()

themes_df = pd.read_csv('data/themes.csv')

merged_df = pd.merge(set_theme_count, themes_df, on='id')
merged_df[:3]

plt.bar(merged_df.name[:10], merged_df.set_count[:10])

plt.figure(figsize=(14,8))
plt.xticks(fontsize=14, rotation=45)
plt.yticks(fontsize=14)
plt.ylabel('Nr of Sets', fontsize=14)
plt.xlabel('Theme Name', fontsize=14)

plt.bar(merged_df.name[:10], merged_df.set_count[:10])

